---
name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        ruby: ["2.6", "2.7", "3.0", "3.1", "head"]
    steps:
      - uses: actions/checkout@v3

      - uses: oxidize-rb/actions/setup-ruby-and-rust@main

      - name: Setup compile cache
        uses: actions/cache@v3
        with:
          path: tmp/
          key: compile-v0-${{ runner.os }}-${{ matrix.ruby }}-${{ hashFiles('**/Cargo.lock', '**/extconf.rb', '**/Gemfile.lock') }}

      - name: Run ruby tests
        run: bundle exec rake

      - name: Lint rust
        run: cargo clippy && cargo fmt --check
