# Adjust this based on your release workflow
name: Cross Gem
on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  cross_gems:
    name: Cross compile gems
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-platform:
          - "arm-linux"
          - "aarch64-linux"
          - "arm64-darwin"
          - "x64-mingw-ucrt"
          - "x86_64-darwin"
          - "x86_64-linux"
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - run: bundle package --all

      - uses: oxidize-rb/cross-gem-action@v6
        with:
          platform: ${{ matrix['ruby-platform'] }}
          setup: |
            rvm all do bundle --local
