# Adjust this based on your release workflow
name: Cross Gem
on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  cross_gems:
    name: Cross compile gems
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-platform:
          - "arm-linux"
          - "aarch64-linux"
          - "arm64-darwin"
          - "x64-mingw-ucrt"
          - "x64-mingw32"
          - "x86_64-darwin"
          - "x86_64-linux"
          - "x86_64-linux-musl"
    steps:
      - uses: actions/checkout@v3

      - uses: oxidize-rb/actions/setup-ruby-and-rust@main
        with:
          ruby-version: "3.1"
          bundler-cache: false
          cargo-cache: true
          cargo-vendor: true
          cache-version: v1

      - uses: oxidize-rb/cross-gem-action@v6
        with:
          platform: ${{ matrix.ruby-platform }}
          version: "0.9.32" # x86_64-linux-musl requires 0.9.32 or higher
